<main class="container py-5">
    <form>
        <fieldset class="my-1">
            <label for="username" class="form-label">
                <?= $this->translator->translate("reg_username_label") ?>
            </label>
            <input type="text" name="username" id="username" class="form-control"/>
        </fieldset>
        <fieldset class="my-1">
            <label for="email" class="form-label">
                <?= $this->translator->translate("reg_email_label") ?>
            </label>
            <input type="email" name="email" id="email" class="form-control"/>
        </fieldset>
        <fieldset class="my-1">
            <label for="password" class="form-label">
                <?= $this->translator->translate("reg_password_label") ?>
            </label>
            <input type="password" name="password" id="password" class="form-control"/>
        </fieldset>
        <fieldset class="my-1">
            <label for="confirm-password" class="form-label">
                <?= $this->translator->translate("reg_conf_password_label") ?>
            </label>
            <input type="password" name="confirm-password" id="confirm-password" class="form-control"/>
        </fieldset>
        <fieldset class="my-4">
            <button type="submit" class="btn btn-primary"><?= $this->translator->translate("reg_submit_button") ?></button>
        </fieldset>
    </form>
    <p>
        <?= $this->translator->translate("reg_login_text") ?> <a href="index.php?route=login"> <?= $this->translator->translate("reg_link_text") ?> </a>
    </p>
</main>